services:
  ubuntu-24:
    image: ghcr.io/peppekerstens/pwsh-pester-ubuntu:24.04
    volumes:
      - ".:/module"
    command: pwsh -NoProfile -Command "Invoke-Pester /module -Output Detailed"
  debian-12:
    image: ghcr.io/peppekerstens/pwsh-pester-debian:12
    volumes:
      - ".:/module"
    command: pwsh -NoProfile -Command "Invoke-Pester /module -Output Detailed"
  fedora-40:
    image: ghcr.io/peppekerstens/pwsh-pester-fedora:40
    volumes:
      - ".:/module"
    command: pwsh -NoProfile -Command "Invoke-Pester /module -Output Detailed"
  opensuse-leap:
    image: ghcr.io/peppekerstens/pwsh-pester-opensuse:leap
    volumes:
      - ".:/module"
    command: pwsh -NoProfile -Command "Invoke-Pester /module -Output Detailed"
  arch:
    image: ghcr.io/peppekerstens/pwsh-pester-arch:latest
    volumes:
      - ".:/module"
    command: pwsh -NoProfile -Command "Invoke-Pester /module -Output Detailed"