name: publish

permissions:
  contents: read
  packages: write


on:
  push:
    tags: ['v*']
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y mono-complete
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'
      - run: nuget pack Update.Linux.nuspec -OutputDirectory out
      - run: dotnet nuget push out/*.nupkg --source https://nuget.pkg.github.com/peppekerstens/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate


